audio:
  samplerate: 16000
  n_fft: 512
  hop_length: 160
  win_length: 400
  n_mels: 80

aug:
  speed_factors: [0.9, 1.0, 1.1]
  speed_prob: 1.0
  vtlp_prob: 0.5
  pitch_prob: 0.3
  gain_prob: 0.7
  noise_prob: 0.3
  rir_prob: 0.1
  specaug_freq_mask_param: 15
  specaug_num_freq_masks: 2
  specaug_time_mask_param: 25
  specaug_num_time_masks: 5
  specaug_time_mask_max_ratio: 0.05

data:
  target_samplerate: 16000
  max_tokens_per_batch: 50000
  num_buckets: 20

decoding:
  beam_width: 100
  alpha: 0.7
  beta: 1.0
